namespace WinFormsCatalog
{
    partial class Form1
    {
        
        private System.ComponentModel.IContainer components = null;

       
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            label1 = new Label();
            filters = new GroupBox();
            resetFilters = new Button();
            checkBox1 = new CheckBox();
            cmbOs = new ComboBox();
            label4 = new Label();
            numPriceMax = new NumericUpDown();
            numPriceMin = new NumericUpDown();
            label3 = new Label();
            cmbProducer = new ComboBox();
            label2 = new Label();
            label5 = new Label();
            cbSort = new ComboBox();
            phonesBindingSource = new BindingSource(components);
            dgvPhones = new DataGridView();
            button1 = new Button();
            txtSearch = new TextBox();
            colName = new DataGridViewTextBoxColumn();
            colProducer = new DataGridViewTextBoxColumn();
            colPrice = new DataGridViewTextBoxColumn();
            colRam = new DataGridViewTextBoxColumn();
            colStorage = new DataGridViewTextBoxColumn();
            colScreen = new DataGridViewTextBoxColumn();
            filters.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)numPriceMax).BeginInit();
            ((System.ComponentModel.ISupportInitialize)numPriceMin).BeginInit();
            ((System.ComponentModel.ISupportInitialize)phonesBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dgvPhones).BeginInit();
            SuspendLayout();
            label1.AutoSize = true;
            label1.Font = new Font("Segoe UI Semibold", 16F, FontStyle.Bold, GraphicsUnit.Point, 204);
            label1.ForeColor = Color.FromArgb(50, 50, 50);
            label1.Location = new Point(12, 9);
            label1.Name = "label1";
            label1.Size = new Size(248, 30);
            label1.TabIndex = 0;
            label1.Text = "Мобильные телефоны";
            filters.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            filters.BackColor = Color.FromArgb(238, 238, 238);
            filters.Controls.Add(resetFilters);
            filters.Controls.Add(checkBox1);
            filters.Controls.Add(cmbOs);
            filters.Controls.Add(label4);
            filters.Controls.Add(numPriceMax);
            filters.Controls.Add(numPriceMin);
            filters.Controls.Add(label3);
            filters.Controls.Add(cmbProducer);
            filters.Controls.Add(label2);
            filters.Font = new Font("Segoe UI", 9.75F, FontStyle.Regular, GraphicsUnit.Point, 204);
            filters.Location = new Point(12, 62);
            filters.Name = "filters";
            filters.Size = new Size(200, 330);
            filters.TabIndex = 1;
            filters.TabStop = false;
            filters.Text = "Фильтры";
            resetFilters.BackColor = Color.FromArgb(238, 238, 238);
            resetFilters.FlatAppearance.MouseDownBackColor = Color.FromArgb(238, 238, 238);
            resetFilters.FlatAppearance.MouseOverBackColor = Color.FromArgb(238, 238, 238);
            resetFilters.FlatStyle = FlatStyle.Flat;
            resetFilters.ForeColor = Color.FromArgb(0, 120, 215);
            resetFilters.Location = new Point(6, 281);
            resetFilters.Name = "resetFilters";
            resetFilters.Size = new Size(187, 34);
            resetFilters.TabIndex = 6;
            resetFilters.Text = "Сбросить фильтры";
            resetFilters.UseVisualStyleBackColor = false;
            checkBox1.AutoSize = true;
            checkBox1.Location = new Point(6, 225);
            checkBox1.Name = "checkBox1";
            checkBox1.RightToLeft = RightToLeft.No;
            checkBox1.Size = new Size(134, 21);
            checkBox1.TabIndex = 8;
            checkBox1.Text = "Только в наличии";
            checkBox1.UseVisualStyleBackColor = true;
            cmbOs.FormattingEnabled = true;
            cmbOs.Location = new Point(6, 187);
            cmbOs.Name = "cmbOs";
            cmbOs.Size = new Size(187, 25);
            cmbOs.TabIndex = 7;
            label4.AutoSize = true;
            label4.Location = new Point(18, 169);
            label4.Name = "label4";
            label4.Size = new Size(26, 17);
            label4.TabIndex = 6;
            label4.Text = "ОС";
            numPriceMax.Location = new Point(104, 123);
            numPriceMax.Name = "numPriceMax";
            numPriceMax.Size = new Size(89, 25);
            numPriceMax.TabIndex = 5;
            numPriceMin.Location = new Point(6, 123);
            numPriceMin.Name = "numPriceMin";
            numPriceMin.Size = new Size(92, 25);
            numPriceMin.TabIndex = 4;
            label3.AutoSize = true;
            label3.Location = new Point(18, 96);
            label3.Name = "label3";
            label3.Size = new Size(100, 17);
            label3.TabIndex = 2;
            label3.Text = "Цена: От... До...";
            cmbProducer.Anchor = AnchorStyles.Left;
            cmbProducer.BackColor = Color.FromArgb(250, 250, 250);
            cmbProducer.FlatStyle = FlatStyle.Flat;
            cmbProducer.FormattingEnabled = true;
            cmbProducer.Location = new Point(6, 47);
            cmbProducer.Name = "cmbProducer";
            cmbProducer.Size = new Size(188, 25);
            cmbProducer.TabIndex = 3;
            label2.AutoSize = true;
            label2.Location = new Point(6, 29);
            label2.Name = "label2";
            label2.Size = new Size(101, 17);
            label2.TabIndex = 2;
            label2.Text = "Производитель";
            label5.AutoSize = true;
            label5.Font = new Font("Segoe UI", 9.75F, FontStyle.Regular, GraphicsUnit.Point, 204);
            label5.Location = new Point(227, 62);
            label5.Name = "label5";
            label5.Size = new Size(80, 17);
            label5.TabIndex = 2;
            label5.Text = "Сортировка";
            cbSort.BackColor = Color.FromArgb(250, 250, 250);
            cbSort.FlatStyle = FlatStyle.Flat;
            cbSort.FormattingEnabled = true;
            cbSort.Location = new Point(227, 83);
            cbSort.Name = "cbSort";
            cbSort.Size = new Size(202, 23);
            cbSort.TabIndex = 3;
            phonesBindingSource.DataSource = typeof(Models.Phones);
            dgvPhones.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            dgvPhones.AutoGenerateColumns = false;
            dgvPhones.BackgroundColor = Color.White;
            dgvPhones.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvPhones.Columns.AddRange(new DataGridViewColumn[] { colName, colProducer, colPrice, colRam, colStorage, colScreen });
            dgvPhones.DataSource = phonesBindingSource;
            dgvPhones.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point, 204);
            dgvPhones.Location = new Point(227, 112);
            dgvPhones.MultiSelect = false;
            dgvPhones.Name = "dgvPhones";
            dgvPhones.ReadOnly = true;
            dgvPhones.RowHeadersVisible = false;
            dgvPhones.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvPhones.Size = new Size(550, 280);
            dgvPhones.TabIndex = 4;
            button1.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            button1.BackColor = Color.FromArgb(0, 120, 215);
            button1.FlatAppearance.BorderSize = 0;
            button1.FlatAppearance.MouseDownBackColor = Color.FromArgb(0, 120, 215);
            button1.FlatAppearance.MouseOverBackColor = Color.FromArgb(0, 120, 215);
            button1.FlatStyle = FlatStyle.Flat;
            button1.Font = new Font("Segoe UI", 10F, FontStyle.Regular, GraphicsUnit.Point, 204);
            button1.ForeColor = Color.White;
            button1.Location = new Point(613, 398);
            button1.Name = "button1";
            button1.Size = new Size(164, 36);
            button1.TabIndex = 5;
            button1.Text = "Подробнее / Купить";
            button1.UseVisualStyleBackColor = false;
            txtSearch.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            txtSearch.BackColor = Color.FromArgb(250, 250, 250);
            txtSearch.BorderStyle = BorderStyle.FixedSingle;
            txtSearch.Location = new Point(453, 83);
            txtSearch.Name = "txtSearch";
            txtSearch.PlaceholderText = " Поиск...";
            txtSearch.Size = new Size(164, 23);
            txtSearch.TabIndex = 9;
            colName.DataPropertyName = "Name";
            colName.HeaderText = "Название";
            colName.Name = "colName";
            colName.ReadOnly = true;
            colName.Width = 220;
            colProducer.DataPropertyName = "Producer";
            colProducer.HeaderText = "Производитель";
            colProducer.Name = "colProducer";
            colProducer.ReadOnly = true;
            colPrice.DataPropertyName = "Price";
            colPrice.HeaderText = "Цена, р.";
            colPrice.Name = "colPrice";
            colPrice.ReadOnly = true;
            colPrice.Width = 70;
            colRam.DataPropertyName = "RamGb";
            colRam.HeaderText = "ОЗУ, гб";
            colRam.Name = "colRam";
            colRam.ReadOnly = true;
            colStorage.DataPropertyName = "StorageGb";
            colStorage.HeaderText = "Память, гб";
            colStorage.Name = "colStorage";
            colStorage.ReadOnly = true;
            colScreen.DataPropertyName = "ScreenSize";
            colScreen.HeaderText = "Экран";
            colScreen.Name = "colScreen";
            colScreen.ReadOnly = true;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(245, 245, 245);
            ClientSize = new Size(800, 450);
            Controls.Add(txtSearch);
            Controls.Add(button1);
            Controls.Add(dgvPhones);
            Controls.Add(cbSort);
            Controls.Add(label5);
            Controls.Add(filters);
            Controls.Add(label1);
            Name = "Form1";
            Text = "Каталог мобильных телефонов";
            Load += Form1_Load;
            filters.ResumeLayout(false);
            filters.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)numPriceMax).EndInit();
            ((System.ComponentModel.ISupportInitialize)numPriceMin).EndInit();
            ((System.ComponentModel.ISupportInitialize)phonesBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)dgvPhones).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private Label label1;
        private GroupBox filters;
        private Label label3;
        private ComboBox cmbProducer;
        private Label label2;
        private NumericUpDown numPriceMax;
        private NumericUpDown numPriceMin;
        private ComboBox cmbOs;
        private Label label4;
        private CheckBox checkBox1;
        private Label label5;
        private ComboBox cbSort;
        private BindingSource phonesBindingSource;
        private DataGridView dgvPhones;
        private Button resetFilters;
        private Button button1;
        private TextBox txtSearch;
        private DataGridViewTextBoxColumn colName;
        private DataGridViewTextBoxColumn colProducer;
        private DataGridViewTextBoxColumn colPrice;
        private DataGridViewTextBoxColumn colRam;
        private DataGridViewTextBoxColumn colStorage;
        private DataGridViewTextBoxColumn colScreen;
    }
}
